goodreads/api/urls.py
from api.views import BookReviewsViewSet
from rest_framework.routers import DefaultRouter
from api.views import UsersListAPIView, BookAuthorsListAPIView
# from api.views import BookReviewDetailAPIView, BookReviewsAPIView,
from django.urls import path

app_name = "api"


urlpatterns = [

    # path("reviews/", BookReviewsAPIView.as_view(), name="review-list"),
    # path("reviews/<int:id>/", BookReviewDetailAPIView.as_view(), name="review-detail"),
    path("users/", UsersListAPIView.as_view(), name="users-list"),
    path("authors/", BookAuthorsListAPIView.as_view(), name="authors-list"),

]


# Linking urls in DRF ViewSet
router = DefaultRouter()
router.register('reviews', BookReviewsViewSet, basename='review')
urlpatterns += router.urls

goodreads/books/urls.py
from django.urls import path
from books.views import BooksView, BookDetailView, AddReviewView, EditReviewView, DeleteReviewView, DeleteCommentView, BookAuthorView


app_name = "books"

urlpatterns = [

    path("", BooksView.as_view(), name='list'),
    path("<int:id>/", BookDetailView.as_view(), name='detail'),
    path("<int:id>/reviews/", AddReviewView.as_view(), name="reviews"),
    path("<int:book_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name="edit-review"),
    path("<int:book_id>/reviews/<int:review_id>/delete_review/", DeleteReviewView.as_view(), name="delete_review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/", DeleteCommentView.as_view(), name="delete_comment"),
    path("<int:id>/author", BookAuthorView.as_view(), name='author'),

]

goodreads/goodreads/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from .views import landing_page, home


urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('home/', home, name='home_page'),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),
    
    
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
]

# Linking static files on the project
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goodreads/books/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone
from users.models import CustomUser



class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_picture = models.ImageField(default="default_cover.jpg")

    def __str__(self):
        return self.title



class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()
    personal_photo = models.ImageField(default='default_pic.jpg')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"



class Bookauthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.book.title} by {self.author.first_name} {self.author.last_name}"

    @property
    def full_name(self):
        return f"{self.author.first_name} {self.author.last_name}"




class BookReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.stars_given} stars by {self.user.username}"

goodreads/books/forms.py
from django import forms

from books.models import BookReview


class BookReviewForm(forms.ModelForm):
    stars_given = forms.IntegerField(min_value=1, max_value=5)
    class Meta:
        model = BookReview
        fields = ('stars_given', 'comment')

goodreads/books/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView
from django.contrib import messages
from books.forms import BookReviewForm
from books.models import Book, BookReview, Bookauthor, Author


# Django generic viewda yozilgan viewlar
# class BooksView(ListView):
#     template_name = "books/list.html"
#     queryset = Book.objects.all().order_by('id')
#     context_object_name = "book_list"
#     paginate_by = 2
#


# class BookDetailView(DetailView):
#     template_name = "books/detail.html"
#     queryset = Book.objects.all()
#     pk_url_kwarg = "id"
#     context_object_name = "book"
#









# Qo'lda yoziladigan viewlar
class BooksView(View):
    def get(self, request):
        book_list = Book.objects.all().order_by('id')
        page_size = request.GET.get('page_size', 2)
        search_query = request.GET.get('q', '')
        if search_query:
            book_list = book_list.filter(title__icontains=search_query)


        # the page is divided into 2
        paginator = Paginator(book_list, page_size)

        # Get default first page
        page_num = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_num)

        contex = {"page_obj":page_obj, "search_query":search_query}
        return render(request, "books/list.html", contex)





class BookDetailView(View):
    def get(self, request, id):
        book = Book.objects.get(id=id)
        book_review_form = BookReviewForm()
        contex = {"book":book, "book_review_form":book_review_form}
        return render(request, "books/detail.html", contex)




class AddReviewView(LoginRequiredMixin, View):
    def post(self, request, id):
        book = Book.objects.get(id=id)
        book_review_form = BookReviewForm(data=request.POST)

        if book_review_form.is_valid():
            BookReview.objects.create(
                book = book,
                user = request.user,
                stars_given = book_review_form.cleaned_data['stars_given'],
                comment = book_review_form.cleaned_data['comment']
            )

            return redirect(reverse("books:detail", kwargs={"id": book.id}))

        return render(request, "books/detail.html", {"book":book, "book_review_form":book_review_form})






class EditReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = BookReview.objects.get(id=review_id)
        review_form = BookReviewForm(instance=review)
        contex = {"book":book, "review":review, "review_form":review_form}

        return render(request, "books/edit_review.html", contex)


    def post(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = BookReview.objects.get(id=review_id)
        review_form = BookReviewForm(instance=review, data=request.POST)
        contex = {"book":book, "review":review, "review_form":review_form}

        if review_form.is_valid():
            review_form.save()
            messages.info(request, "You have successfully edited your comment!")
            return redirect(reverse("books:detail", kwargs={"id": book.id}))

        return render(request, "books/edit_review.html", contex)





class DeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = BookReview.objects.get(id=review_id)
        contex = {"book":book, "review":review}
        return render(request, "books/delete_review.html", contex)




class DeleteCommentView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = BookReview.objects.get(id=review_id)

        review.delete()
        messages.success(request, "you have successfully deleted your comment")
        return redirect(reverse("books:detail", kwargs={"id": book.id}))







class BookAuthorView(View):
    def get(self, request, id):
        author = Author.objects.get(id=id)
        contex = {"author":author}
        return render(request, 'books/author.html', contex)

goodreads/books/templates/books/author.html
{% extends "base.html" %}
{% block title %}Author{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-6" style="width: 28%;">
            <div class="card" style="width: 18rem;">
                <img class="author_img" src="{{ author.personal_photo.url }}" alt="Author image">
            </div>

        </div>
        <div class="col-4">
             <h2>{{ author.first_name }} {{ author.last_name }}</h2>
            <p class="card-text">{{ author.bio }}</p>

        </div>
    </div>
</div>


<h3 class="mb-5 mt-5 text-center">{{ author.first_name }} {{ author.last_name }}'s Books</h3>
<hr><br>
<div class="container">
    <div class="row">
            {% for book_details in author.bookauthor_set.all %}
     <div class="col-4">
           <div class="card" style="width: 22rem;">
            <img src="{{ book_details.book.cover_picture.url }}" class="card_book" alt="Book image">
            <div class="card-body">
            <h5 class="card-title">{{ book_details.book.title }}</h5>
            <p class="card-text">{{ book_details.book.description | slice:"200" }}...</p>
            <a href="{% url 'books:detail' book_details.book.id %}" class="btn btn-primary" role="button">Reading</a>
         </div>
    </div>
  </div>

            {% endfor %}

    </div>
</div>

{% endblock %}

goodreads/books/templates/books/delete_review.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Edit review{% endblock %}



{% block content %}

<h3>Are you sure you want to delete this review?</h3>


    <p>
        <b>Book:</b> {{ book.title }}
    </p>
    <p>
        <b>Review:</b>  {{ review.comment }}
    </p>

    <a class="btn btn-outline-danger" href="{% url 'books:delete_comment' book.id review.id %}" style="margin-right: 10px">Yes</a>   <a class="btn btn-outline-primary" href="{% url 'books:detail' book.id %}">No</a>




{% endblock %}

goodreads/books/templates/books/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Book Detail page{% endblock %}

{% block content %}

<div class="row mb-5">
                    <div class="col-2 me-5">
                        <img class="cover_pic" src="{{ book.cover_picture.url }}" alt="cover image">
                    </div>
                    <div class="col-6 ms-5">
                        <h2>{{ book.title}}</h2>



                        <span class="text-capitalize">
                            <b>Authored by</b>
                            {% for book_author in book.bookauthor_set.all %}
                                {% if forloop.last %}
                                    <a class="text_dec" href="{% url 'books:author' book_author.author.id %}" >{{ book_author.full_name }}</a>
                                {% else %}
                                    <a class="text_dec" href="{% url 'books:author' book_author.author.id %}">{{ book_author.full_name }}</a>,
                                {% endif %}
                            {% endfor %}

                        </span>

                        <p>{{ book.description }}</p>

                    </div>
                </div>


<div class="row mb-5">
    <div class="col-6">

        <form method="post" action="{% url 'books:reviews' book.id %}">

            {% csrf_token %}
            {{ book_review_form | crispy }}
            <button type="submit" class="btn btn-success">Add review</button>
        </form>

    </div>
</div>








{% if book.bookreview_set.exists %}
    <h3>Reviews</h3>
    <hr>

    {% for review in book.bookreview_set.all %}

        <div class="row mb-5 mt-4">
            <div class="col-1">
                <img class="small-profile-pic" src="{{ review.user.profile_picture.url }}">
            </div>
            <div class="col-7">
                <b>{{ review.user.username }}</b> rated it {{ review.stars_given }} stars <span class="fst-italic">{{ review.created_at }}</span>
                {% if review.user == request.user %}
                <a href="{% url 'books:edit-review' book.id review.id %}"><i class="bi bi-pen"></i></a>
                <a href="{% url 'books:delete_review' book.id review.id %}"><i class="bi bi-trash"></i></a>
                {% endif %}
                <p class="font-monospace">{{ review.comment }}</p>

            </div>
        </div>


    {% endfor %}
{% endif %}
    <a href="{% url 'books:list' %}" role="button" class="btn btn-primary btn-sm">All books</a>
<br><br>

{% endblock %}

goodreads/books/templates/books/edit_review.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Edit review{% endblock %}



{% block content %}

<h3>Edit Review</h3>



<div class="row mb-5">
    <div class="col-6">

        <form method="post" action="{% url 'books:edit-review' book.id review.id %}">

            {% csrf_token %}
            {{ review_form | crispy }}
            <button type="submit" class="btn btn-success">Save</button>
        </form>

    </div>
</div>



{% endblock %}

goodreads/books/templates/books/list.html
{% extends "base.html" %}
{% block title %}Books page{% endblock %}

{% block content %}

<h1>Books</h1>
<br>

<div class="row mb-3">
    <div class="col-4">
        <form method="get" class=" d-flex me-2">
            <input type="text" class="form-control me-2" placeholder="Search" name="q" value="{{ search_query }}">      <! -- viewda 'q' dan foydalanib requestdan keyotgan valueni olamiz -->
            <button class="btn btn-success">Search</button>
        </form>
    </div>
</div>








    {% if page_obj %}

            {% for book in page_obj %}
                <div class="row mb-4">
                    <div class="col-2 me-5">
                        <img class="cover_pic" src="{{ book.cover_picture.url }}" alt="cover image">
                    </div>
                    <div class="col-6 ms-5">
                        <a href="{% url 'books:detail' book.id %}" style="text-decoration: none;"><h4>{{ book.title}}</h4></a>
                        <p>{{ book.description }}</p>

                    </div>
                </div>



            {% endfor %}

        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
                {% endif %}

                <li class="page-item active">
                    <a href="#" class="page-link">{{ page_obj.number }}</a>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last&raquo;</a></li>
                {% endif %}
            </ul>
        </nav>

    {% else %}
        <p>No books found.</p>
    {% endif %}

{% endblock %}