goodreads/api/urls.py
from api.views import BookReviewsViewSet
from rest_framework.routers import DefaultRouter
from api.views import UsersListAPIView, BookAuthorsListAPIView
# from api.views import BookReviewDetailAPIView, BookReviewsAPIView,
from django.urls import path

app_name = "api"


urlpatterns = [

    # path("reviews/", BookReviewsAPIView.as_view(), name="review-list"),
    # path("reviews/<int:id>/", BookReviewDetailAPIView.as_view(), name="review-detail"),
    path("users/", UsersListAPIView.as_view(), name="users-list"),
    path("authors/", BookAuthorsListAPIView.as_view(), name="authors-list"),

]


# Linking urls in DRF ViewSet
router = DefaultRouter()
router.register('reviews', BookReviewsViewSet, basename='review')
urlpatterns += router.urls

goodreads/books/urls.py
from django.urls import path
from books.views import BooksView, BookDetailView, AddReviewView, EditReviewView, DeleteReviewView, DeleteCommentView, BookAuthorView


app_name = "books"

urlpatterns = [

    path("", BooksView.as_view(), name='list'),
    path("<int:id>/", BookDetailView.as_view(), name='detail'),
    path("<int:id>/reviews/", AddReviewView.as_view(), name="reviews"),
    path("<int:book_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name="edit-review"),
    path("<int:book_id>/reviews/<int:review_id>/delete_review/", DeleteReviewView.as_view(), name="delete_review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/", DeleteCommentView.as_view(), name="delete_comment"),
    path("<int:id>/author", BookAuthorView.as_view(), name='author'),

]

goodreads/goodreads/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from .views import landing_page, home


urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('home/', home, name='home_page'),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),
    
    
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
]

# Linking static files on the project
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goodreads/users/urls.py
from django.urls import path
from users.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView



app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name='register'),
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    path("profile/", ProfileView.as_view(), name='profile'),
    path("profile/edit/", ProfileUpdateView.as_view(), name='profile_edit'),

]

goodreads/templates/base.html
<!--  Linking static files  -->
{% load static %}
{% url 'home_page' as home_page_url %}
{% url 'books:list' as books_list %}
{% url 'users:profile' as users_profile %}
{% url 'users:logout' as users_logout %}
{% url 'users:login' as users_login %}
{% url 'users:profile_edit'  as users_profile_edit %}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block title %} Goodreads {% endblock %} </title>

    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
<!--  Static files  -->
  <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">

</head>


<body class="mx-5" style="background: #e0dcd0;">
<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-5">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'landing_page' %}">Goodreads</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == books_list %} active {% endif %}" aria-current="page" href="{{ books_list }}">Books</a>
        </li>

         <li class="nav-item">
          <a class="nav-link {% if request.path == home_page_url %} active {% endif %}" aria-current="page" href="{{ home_page_url }}">Home</a>
        </li>


      </ul>

        <div class="me-5">
            {% if request.user.is_authenticated %}
            <ul class="navbar-nav">
                 <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle {% if request.path == users_profile or request.path == users_profile_edit %} active {% endif %}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {{ request.user.username }}
                </a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{{ users_profile }}">Profile</a></li>
                <li><a class="dropdown-item" href="{{ users_logout }}">Logout</a></li>
          </ul>
            </li>
            </ul>

            {% else %}
                <a href="{{ users_login }}" class="btn btn-primary">Login</a>
            {% endif %}
        </div>

    </div>
  </div>
</nav>
<br>

<div class="container">
    {% if messages %}
         <div class="mt-4">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
            <br><br>
         </div>
    {% endif %}

</div>


{% block content %}
{% endblock %}







<!-- JavaScript Bundle with Popper -->
<script src="https://kit.fontawesome.com/dabef8e6a1.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

goodreads/templates/default.html
{% load static %}

{% url 'home_page' as home_page_url %}
{% url 'books:list' as books_page_url %}
{% url 'users:profile' as profile_page_url %}
{% url 'users:profile-edit' as profile_edit_page_url %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">


    <title>{% block title %}Goodreads clone{% endblock %}</title>
</head>
<body class="bg-light">
{#{% if request.user.is_authenticated %}#}
{#    <nav class="navbar navbar-expand-lg navbar-light base-navbar sticky-top shadow-sm px-5">#}
{#        <div class="container-fluid">#}
{#            <a class="navbar-brand logo-size " href="{% url 'landing_page' %}">good<b>reads</b></a>#}
{#            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"#}
{#                    data-bs-target="#navbarSupportedContent"#}
{#                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">#}
{#                <span class="navbar-toggler-icon"></span>#}
{#            </button>#}
{#            <div class="collapse navbar-collapse" id="navbarSupportedContent">#}
{#                <ul class="navbar-nav me-auto mb-2 mb-lg-0">#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link {% if request.path == home_page_url %}active{% endif %}" aria-current="page"#}
{#                           href="{% url 'home_page' %}">Home</a>#}
{#                    </li>#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link {% if request.path == books_page_url %}active{% endif %}" aria-current="page"#}
{#                           href="{% url 'books:list' %}">My Books</a>#}
{#                    </li>#}
{#                    <li class="nav-item dropdown">#}
{#                        <a class="nav-link dropdown-toggle" href="#" role="button"#}
{#                           data-bs-toggle="dropdown" aria-expanded="false">#}
{#                            Browse#}
{#                        </a>#}
{#                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#                            <li><a class="dropdown-item" href="#">Action</a></li>#}
{#                            <li><a class="dropdown-item" href="#">Another action</a></li>#}
{#                            <li>#}
{#                                <hr class="dropdown-divider">#}
{#                            </li>#}
{#                            <li><a class="dropdown-item" href="#">Something else here</a></li>#}
{#                        </ul>#}
{#                    </li>#}
{#                    <li class="nav-item dropdown">#}
{#                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"#}
{#                           data-bs-toggle="dropdown" aria-expanded="false">#}
{#                            Community#}
{#                        </a>#}
{#                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#                            <li><a class="dropdown-item" href="#">Action</a></li>#}
{#                            <li><a class="dropdown-item" href="#">Another action</a></li>#}
{#                            <li>#}
{#                                <hr class="dropdown-divider">#}
{#                            </li>#}
{#                            <li><a class="dropdown-item" href="#">Something else here</a></li>#}
{#                        </ul>#}
{#                    </li>#}
{#                </ul>#}
{#                {% if request.user.is_authenticated %}#}
{#                    <form class="d-flex me-4">#}
{#                        <input class="form-control me-1" type="search" placeholder="Search book " aria-label="Search"#}
{#                               name="q" value="{{ search_query }}">#}
{#                        <button class="btn btn-outline-secondary" type="submit"><i class="bi bi-search"></i></button>#}
{#                    </form>#}
{#                    <a class="btn btn-outline-dark me-1" href="#"><i class="bi bi-bell"></i></a>#}
{#                    <a class="btn btn-outline-dark me-1" href="#"><i class="bi bi-chat-text"></i></a>#}
{#                    <a class="btn btn-outline-dark me-1" href="#"><i class="bi bi-envelope"></i></a>#}
{#                    <a class="btn btn-outline-dark me-1" href="#"><i class="bi bi-people"></i></a>#}
{#                    <div class="btn-group">#}
{#                        <button type="button" class="btn btn-outline-dark dropdown-toggle" data-bs-toggle="dropdown"#}
{#                                aria-expanded="false">#}
{#                            <i class="bi bi-person-check"></i>#}
{#                        </button>#}
{#                        <ul class="dropdown-menu dropdown-menu-md-end">#}
{#                            <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>#}
{#                            <li><a class="dropdown-item" href="#">Friends</a></li>#}
{#                            <li><a class="dropdown-item" href="#">Groups</a></li>#}
{#                            <li><a class="dropdown-item" href="#">Discussion</a></li>#}
{#                            <li><a class="dropdown-item" href="#">Comments</a></li>#}
{#                            <li>#}
{#                                <hr class="dropdown-divider">#}
{#                            </li>#}
{#                            <li><a class="dropdown-item" href="#">Account settings</a></li>#}
{#                            <li><a class="dropdown-item" href="#">Help</a></li>#}
{#                            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Sign out</a></li>#}
{#                        </ul>#}
{#                    </div>#}
{#                {% else %}#}
{#                    <a class="btn btn-outline-secondary" href="{% url 'users:login' %}">Login</a>#}
{#                {% endif %}#}
{#            </div>#}
{#        </div>#}
{#    </nav>#}
{#    <div class="container py-5">#}
{#        {% if messages %}#}
{#            {% for message in messages %}#}
{#                <div class="alert alert-{{ message.tags }}" role="alert">#}
{#                    {{ message }}#}
{#                </div>#}
{#            {% endfor %}#}
{#        {% endif %}#}
{#        {% block content %}#}
{##}
{##}
{#        {% endblock %}#}
{#    </div>#}
{#{% else %}#}
<nav class="navbar navbar-expand-lg navbar-light base-navbar sticky-top px-5 landing-navbar">
    <div class="container-fluid px-5">
        <a class="navbar-brand logo-size fs-1 text-secondary" href="{% url 'landing_page' %}">good<span
                class="text-dark">reads-clone</span></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>


<img src="{% static 'image/HomepageMasthead_Desktop.png' %}" alt="Home page image">
<div class="row ">
    <div class="card card-site">
        <div class="card-body text-center ">
            <h6 class="mt-2">Discover & read more</h6>
            <a href="#" class="l-link p-2 btn btn-primary my-3 disabled"><i class="bi bi-facebook"></i>
                Continue with Facebook</a><br>
            <a href="#" class="l-link p-2 btn btn-warning disabled"><i class="bi bi-google"></i> Continue
                with Google</a><br>
            <a href="#" class="l-link border-dark p-2 btn btn-light my-3 disabled"><i class="bi bi-apple"></i> Continue
                with Apple</a><br>
            <a href="{% url 'users:register' %}" class="l-link p-2 btn btn-secondary mb-3">Sign Up
                with email</a><br>

            <p class="p1">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            <hr>
            <p>Already a member? <a href="{% url 'users:login' %}" style="text-decoration: none;">Sign In</a></p>
        </div>
    </div>
</div>



</body>
</html>

goodreads/templates/home_page.html
{% extends "base.html" %}

{% block title %} Home page {% endblock %}

{% block content %}

<h1>Home page</h1>





{% for review in page_obj %}

<div class="container posts-content">
    <div class="row">
        <div class="col-lg-6">
            <div class="card mb-4">
                <div class="card-body">
                    <div class="media mb-3">
                        <img src="{{ review.user.profile_picture.url }}"
                             class="small-profile-pic" alt="">
                        <div class="media-body ml-3">
                           <b>{{ review.user.username }}</b> rated this book {{ review.stars_given }} stars
                            <div class="text-muted small">{{ review.created_at |date:'M d, Y'}}</div>
                        </div>
                    </div>

                    <p>
                        {{ review.comment | truncatechars:200 }}
                    </p>
                        <img class="cover_pic_center" src="{{ review.book.cover_picture.url }}" alt="cover image">
                </div>

            </div>
        </div>

    </div>
</div>
{% endfor %}

        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
                {% endif %}

                <li class="page-item active">
                    <a href="#" class="page-link">{{ page_obj.number }}</a>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last&raquo;</a></li>
                {% endif %}
            </ul>
        </nav>



{% endblock %}

goodreads/templates/landing.html
{% extends "base.html" %}

{% block content %}
<h1>Landing page</h1>

<p>
    Goodreads is an American social cataloging website and a subsidiary of Amazon[1] that allows individuals to search its database of books, annotations, quotes, and reviews. AbstractUsers can sign up and register books to generate library catalogs and reading lists. They can also create their own groups of book suggestions, surveys, polls, blogs, and discussions. The website's offices are located in San Francisco.[2]

    Goodreads was founded in December 2006 and launched in January 2007 by Otis Chandler and Elizabeth Khuri Chandler.[3][4] In December 2007, the site had 650,000 members[5] and 10,000,000 books had been added.[6] By July 2012, the site reported 10 million members, 20 million monthly visits, and thirty employees.[7] On March 28, 2013, Amazon announced its acquisition of Goodreads,[8] and by July 23, 2013, Goodreads announced their AbstractUser base had grown to 20 million members.[9]
</p>

{% endblock %}